---
title: "model_selection"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{model_selection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(plausi)
library(caret)
```


```{r}


sundata_369 <- readRDS("C:/gitrepos/plausi/data/20200927/sundata_369.RDS")

features <- readRDS("C:/gitrepos/plausi/data/20200927/features2020-09-27.RDS")

unique(sundata_369$gemwkid)

# wide to long
pred_act <- sundata_369 %>% 
  select(gemeinde,gemwkid, artsort, jastimmeninprozent) %>% 
  tidyr::spread(artsort,jastimmeninprozent)

# Hier code einbauen der nur Vorlagen mit mehr als 5-10 einträgen aufweist

pred_all <- pred_act %>% 
  filter(gemwkid != 9010)%>% 
  rename(v_gemwkid = gemwkid)%>% 
  # allenfalls auf right-join umstellen
  right_join(features, by = c("v_gemwkid")) %>% 
  #hack um gemeindelabels für Gemeinden die noch nicht auf gelb sind beizubehalten
  mutate(gemeinde=v_gemeinde) %>% 
  select(-v_gemeinde)


loocv <- caret::trainControl(method = "LOOCV", number = 10)
cv10 <- caret::trainControl(method = "cv", number = 10)

earth <- 
  cv_model_mars <- caret::train(
    Eidg3 ~ ., 
    data = pred_all %>% select(-gemeinde, -v_gemwkid) %>% drop_na(),
    method = "gcvEarth",
    trControl = loocv
  )

glm <- 
  cv_model_mars <- caret::train(
    Eidg3 ~ ., 
    data = pred_all %>% select(-gemeinde, -v_gemwkid) %>% drop_na(),
    method = "glmnet",
    trControl = cv10
  )

tox_svm <- train(  Eidg3 ~ ., 
    data = pred_all %>% select(-gemeinde, -v_gemwkid) %>% drop_na(),
                 method = "svmRadial", 
                 metric = "wRMSE",
                 maximize = FALSE,
                 tuneLength = 10,trControl = cv10)


tg <- expand.grid(shrinkage = seq(0.1, 1, by = 0.2), 
                  interaction.depth = c(1, 3, 7, 10),
                  n.minobsinnode = c(2, 5, 10),
                  n.trees = c(100, 300, 500, 1000))

gbm <- 
  cv_model_mars <- caret::train(
    Eidg3 ~ ., 
    data = pred_all %>% select(-gemeinde, -v_gemwkid) %>% drop_na(),
    method = "ranger",
    trControl = cv10
  )


mods <- resamples(list(earth=earth2, svm=tox_svm, glm=glm,ranger=gbm))

summary(mods)


```

